# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79d8410894e066a429b5276955158c96da99d09c8be092be3042d8ac5e9f2243183014773431ca465cf5001fc7370bf3430ec94dd744aecc62755e51c7d7213a

test:
  secret_key_base: 775dc72101e5f94fd870b2a285d602bc85d5211261bfabe9cf12e066ab1ec0d8e8920307ae40eb0824635aca9188acb21dcbe200613671540e2a646aae7106f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
